biblioteca-lbd:
  db:
    active: dbinit
    db-name: postgres
    postgresUrl: localhost
  spring-boot:
    environment: development
    springbootUrl: localhost
  frontend:
    baseUrl: http://localhost:3000/
server:
  port: '3001'
  host: http://${biblioteca-lbd.spring-boot.springbootUrl}}/
spring:
  datasource:
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${biblioteca-lbd.db.postgresUrl}:5432/${biblioteca-lbd.db.db-name}
    hikari:
      maxLifetime: '1800000'
      connectionTimeout: '500000'
      idleTimeout: '60000'
      maximumPoolSize: '10'
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
    schemas: public
    url: jdbc:postgresql://${biblioteca-lbd.db.postgresUrl}:5432/${biblioteca-lbd.db.db-name}
    user: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update
      hbm2ddl:
        auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          default_schema: public
          #          audit_table_suffix: z_aud
          revision_field_name: rev
          revision_type_field_name: revtype